---
title: "R Notebook"
output: html_notebook
---


```{r}
library(datasets)
library(Hmisc)
library(grid)
library(ggplot2)
```


```{r}
df <- read.csv('stock_details_5_years.csv')

df_googl <- df[df$Company == "GOOGL", ]
df_googl


```

```{r}
ts.plot(df_googl$Open, xlab="Time", ylab = 'Googl Opening Prices')
```


```{r}
df_googl$Open_lag1 <- Lag(df_googl$Open,1)
df_googl$Open_lead1 <- Lag(df_googl$Open,-1)
df_googl$Open_change <- (df_googl$Open_lead1 - df_googl$Open_lag1)/2

plot(df_googl$Open_change,type='l', xlab = "Time in 10 min increments", ylab =" Change in Body Temp")
```

```{r}
plot(density(diff(df_googl$Open, lag = 1, differences = 1)))

```


```{r}
Open_diff <- diff(df_googl$Open, lag = 1)


plot(Open_diff, xlab = "Time in days", ylab ="Change in Opening Price")

```
Around day 800 something happens, after which the data is more spread out than in the beginning.

```{r}
library(lubridate)

df_googl$Date2 <- ymd_hms(df_googl$Date)  # Convert to POSIXct

ggplot(data=df_googl,aes(x=Date2,y=Open))+
  geom_segment(aes(xend=Date2,yend=Open+Open_diff),arrow=arrow(length=unit(.2,"cm")))+
  stat_density2d(aes(colour=..level..))+
    labs(
    title = "GOOGL Opening Stock - 2D Vector Density Plot",
    x = "Date",
    y = "Opening Price",
    colour = "Density Level"
  )
```

```{r}
## TEST DATA

#Open_diff2 <- append(Open_diff, 0)
#length(Open_diff2)

openLM <- lm(Open_diff2~Open, data=df_googl)
summary(openLM)
```

```{r}
plot(openLM)
```

```{r}


```

